### ISSUE TITLE
Mod will not launch no matter what I try.

### ISSUE THREAD

**Issue by CotoDude** [Ladysnake/Astronomical#29]
Hello! I have installed all known dependencies (Card. Components API, Quilted fabric API), and yet it gives the error:
(Log quote starts here)
net.minecraft.class_148: Rendering overlay
	at net.minecraft.class_757.method_3192(class_757.java:877) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-1.19.2.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557) [quilt-loader-0.26.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.26.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.26.0.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
(Log quote ends here)

[Here's the log](https://mclo.gs/lRwuzbm)

**Comment by CotoDude** [comment]
Figured out how to get it to work. Sorry bout that.
Basically, if you're a non-dev tryna figure this out:
downgrade quilted fabric to the second newest version. The current one (as of june 5 2024) doesnt work fsr.
