### ISSUE TITLE
When the game tries to load a planet/star it crashes maybe it is a mod conflict. Any help, please?

### ISSUE THREAD

**Issue by AlsoNotLynx** [Ladysnake/Astronomical#3]
[14:33:04] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_918.method_4026(class_918.java:360) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_36543(class_918.java:340) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_27951(class_918.java:336) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1762(class_329.java:1257) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1759(class_329.java:579) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1753(class_329.java:204) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-1.19.2.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.22.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: class doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder tried to access field com.sammy.lodestone.systems.rendering.VFXBuilders$WorldVFXBuilder.r (doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder and com.sammy.lodestone.systems.rendering.VFXBuilders$WorldVFXBuilder are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @5bcab519)
	at doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder.renderSphere(AstraWorldVFXBuilder.java:184) ~[astronomical-1.0.01.19.2.i0:0/:?]
	at doctor4t.astronomical.client.AstronomicalClient.renderAstralObject(AstronomicalClient.java:84) ~[astronomical-1.0.01.19.2.i0:0/:?]
	at net.minecraft.class_918.handler$emf000$astronomical$renderItem(class_918.java:4572) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_23179(class_918.java) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_4021(class_918.java:307) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_4026(class_918.java:350) ~[minecraft-1.19.2.i0:0/:?]

**Comment by AlsoNotLynx** [comment]
![image](https://github.com/Ladysnake/Astronomical/assets/156795408/53bebc26-7291-4b32-b1a5-c9cde1ddb29b)
![image](https://github.com/Ladysnake/Astronomical/assets/156795408/a3acf33d-4704-48a6-9e66-cb5af934e37b)
mod list if u need
only the mods with a tick are working

**Comment by AlsoNotLynx** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder.renderSphere(AstraWorldVFXBuilder.java:184)
	at doctor4t.astronomical.client.AstronomicalClient.renderAstralObject(AstronomicalClient.java:84)
	at net.minecraft.class_918.handler$emf000$astronomical$renderItem(class_918.java:4572)
	at net.minecraft.class_918.method_23179(class_918.java)
	at net.minecraft.class_918.method_4021(class_918.java:307)
	at net.minecraft.class_918.method_4026(class_918.java:350)
	at net.minecraft.class_918.method_36543(class_918.java:340)
	at net.minecraft.class_918.method_27951(class_918.java:336)
	at net.minecraft.class_329.method_1762(class_329.java:1257)
	at net.minecraft.class_329.method_1759(class_329.java:579)
	at net.minecraft.class_329.method_1753(class_329.java:204)

-- Item being rendered --
Details:
	Item Type: nano_planet
	Item Damage: 0
	Item NBT: {astronomical:{color1:-6100194,color2:-91984,size:10,texture:"ICE"}}
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:350)
	at net.minecraft.class_918.method_36543(class_918.java:340)
	at net.minecraft.class_918.method_27951(class_918.java:336)
	at net.minecraft.class_329.method_1762(class_329.java:1257)
	at net.minecraft.class_329.method_1759(class_329.java:579)
	at net.minecraft.class_329.method_1753(class_329.java:204)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['DaRealLynx'/47, l='ClientLevel', x=-6.23, y=-60.00, z=5.16]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 661 game time, 661 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by JustRed23** [comment]
If possible, please upload the full client log to [mclo.gs](https://mclo.gs/) as this would make it easier to read

**Comment by AlsoNotLynx** [comment]
> If possible, please upload the full client log to [mclo.gs](https://mclo.gs/) as this would make it easier to read

One sec man
Its 10 pm in my country

**Comment by JustRed23** [comment]
> > If possible, please upload the full client log to [mclo.gs](https://mclo.gs/) as this would make it easier to read
> 
> One sec man Its 10 pm in my country

nw, take your time

**Comment by AlsoNotLynx** [comment]
> > > If possible, please upload the full client log to [mclo.gs](https://mclo.gs/) as this would make it easier to read
> > 
> > 
> > One sec man Its 10 pm in my country
> 
> nw, take your time

https://mclo.gs/oh7rTIB

**Comment by JustRed23** [comment]
Main error can be found [here](https://mclo.gs/oh7rTIB#L3113), just some good ol private access errors

**Comment by AlsoNotLynx** [comment]
> Main error can be found [here](https://mclo.gs/oh7rTIB#L3113), just some good ol private access errors

Yes i can see that
I was  reading the logs myself and thought
What da hail is com.sammy.lodestone

**Comment by JadedChara** [comment]
> > Main error can be found [here](https://mclo.gs/oh7rTIB#L3113), just some good ol private access errors
> 
> Yes i can see that I was reading the logs myself and thought What da hail is com.sammy.lodestone

Lodestone's an API for rendering effects iirc. Think Rat's Airship mod.

**Comment by AlsoNotLynx** [comment]
> > > Main error can be found [here](https://mclo.gs/oh7rTIB#L3113), just some good ol private access errors
> > 
> > Yes i can see that I was reading the logs myself and thought What da hail is com.sammy.lodestone
> 
> Lodestone's an API for rendering effects iirc. Think Rat's Airship mod.

I hope rat will fix it
I dont want to delete the airship cuz of the plushies

**Comment by JustRed23** [comment]
Okay, so I found a solution. Download the latest version of lodestone api and put it in your mods folder.

Known working: [download](https://jitpack.io/com/github/Arathain/LodestoneLib-Quilt/e4925a6faf/LodestoneLib-Quilt-e4925a6faf.jar)

**Comment by AlsoNotLynx** [comment]
> Okay, so I found a solution. Download the latest version of lodestone api and put it in your mods folder.
> 
> Known working: [download](https://jitpack.io/com/github/Arathain/LodestoneLib-Quilt/e4925a6faf/LodestoneLib-Quilt-e4925a6faf.jar)

Il try it asap as i get home

**Comment by AlsoNotLynx** [comment]
> Okay, so I found a solution. Download the latest version of lodestone api and put it in your mods folder.
> 
> Known working: [download](https://jitpack.io/com/github/Arathain/LodestoneLib-Quilt/e4925a6faf/LodestoneLib-Quilt-e4925a6faf.jar)

YOU ARE A FING LEGEND THANK YOU SO MUCH
